package io.namei.agent.adapter.sqlite;

enum ChannelLedgerFaultPoint {
  EVENT_RECORDED_BEFORE_COMMIT,
  TURN_STARTED_BEFORE_COMMIT,
  TERMINAL_RECORDED_BEFORE_COMMIT,
  DELIVERY_CLAIMED_BEFORE_COMMIT,
  DELIVERY_OUTCOME_BEFORE_COMMIT,
  RECOVERY_BEFORE_COMMIT,
  CLEANUP_BEFORE_COMMIT
}
