package io.namei.agent.kernel.cutover;

public enum CutoverStableCode {
  CUTOVER_CONTRACT_INVALID,
  CUTOVER_STATE_INVALID,
  CUTOVER_PRODUCTION_FORBIDDEN,
  SANDBOX_UNSAFE,
  PRECONDITION_MISSING,
  BACKUP_INVALID,
  DIFFERENCE_THRESHOLD_EXCEEDED
}
